//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDVELH_WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SaveOfManualEnglish {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SaveOfManualEnglish() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDVELH_WPF.Resources.SaveOfManualEnglish", typeof(SaveOfManualEnglish).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay the required sum (10 gold ).
        /// </summary>
        internal static string Paragraph12BuyEvent1 {
            get {
                return ResourceManager.GetString("Paragraph12BuyEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the war hammer.
        /// </summary>
        internal static string Paragraph148LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph148LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the strange sword.
        /// </summary>
        internal static string Paragraph15LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph15LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the gold.
        /// </summary>
        internal static string Paragraph184LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph184LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the sword.
        /// </summary>
        internal static string Paragraph184LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph184LootEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the food.
        /// </summary>
        internal static string Paragraph184LootEvent3 {
            get {
                return ResourceManager.GetString("Paragraph184LootEvent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the letter.
        /// </summary>
        internal static string Paragraph193LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph193LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the gold.
        /// </summary>
        internal static string Paragraph197LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph197LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the sabre.
        /// </summary>
        internal static string Paragraph197LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph197LootEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the food.
        /// </summary>
        internal static string Paragraph199LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph199LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the dagger.
        /// </summary>
        internal static string Paragraph20LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph20LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the food.
        /// </summary>
        internal static string Paragraph20LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph20LootEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the mace.
        /// </summary>
        internal static string Paragraph243LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph243LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the dagger.
        /// </summary>
        internal static string Paragraph267LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph267LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the letter.
        /// </summary>
        internal static string Paragraph267LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph267LootEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accet his offer (10 gold).
        /// </summary>
        internal static string Paragraph269BuyEvent1 {
            get {
                return ResourceManager.GetString("Paragraph269BuyEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the baton.
        /// </summary>
        internal static string Paragraph290LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph290LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the dagger.
        /// </summary>
        internal static string Paragraph291LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph291LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the spear.
        /// </summary>
        internal static string Paragraph291LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph291LootEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the spear.
        /// </summary>
        internal static string Paragraph305LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph305LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the hammer.
        /// </summary>
        internal static string Paragraph307LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph307LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the food.
        /// </summary>
        internal static string Paragraph307LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph307LootEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the soap.
        /// </summary>
        internal static string Paragraph315LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph315LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the dagger.
        /// </summary>
        internal static string Paragraph319LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph319LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the spear.
        /// </summary>
        internal static string Paragraph346LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph346LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the sabre.
        /// </summary>
        internal static string Paragraph347LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph347LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the lighter.
        /// </summary>
        internal static string Paragraph347LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph347LootEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take the torch.
        /// </summary>
        internal static string Paragraph347LootEvent3 {
            get {
                return ResourceManager.GetString("Paragraph347LootEvent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratz, you can exit now.
        /// </summary>
        internal static string Paragraph350LootEvent1 {
            get {
                return ResourceManager.GetString("Paragraph350LootEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should have exited by now.
        /// </summary>
        internal static string Paragraph350LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph350LootEvent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept his offer (2 gold).
        /// </summary>
        internal static string Paragraph46BuyEvent1 {
            get {
                return ResourceManager.GetString("Paragraph46BuyEvent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a sword.
        /// </summary>
        internal static string Paragraph62LootEvent2 {
            get {
                return ResourceManager.GetString("Paragraph62LootEvent2", resourceCulture);
            }
        }
    }
}
