//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDVELH_WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDVELH_WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agi.
        /// </summary>
        internal static string agi {
            get {
                return ResourceManager.GetString("agi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité :.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hache.
        /// </summary>
        internal static string Axe {
            get {
                return ResourceManager.GetString("Axe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sac à Dos :.
        /// </summary>
        internal static string BackPack {
            get {
                return ResourceManager.GetString("BackPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bâton.
        /// </summary>
        internal static string Baton {
            get {
                return ResourceManager.GetString("Baton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Combat.
        /// </summary>
        internal static string Battling {
            get {
                return ResourceManager.GetString("Battling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monstre.
        /// </summary>
        internal static string Beast {
            get {
                return ResourceManager.GetString("Beast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Animale.
        /// </summary>
        internal static string BeastWhisperer {
            get {
                return ResourceManager.GetString("BeastWhisperer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas manger plus, vous êtes déjà rassasié !.
        /// </summary>
        internal static string CantEat {
            get {
                return ResourceManager.GetString("CantEat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to capacités.
        /// </summary>
        internal static string Capacities {
            get {
                return ResourceManager.GetString("Capacities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacités :.
        /// </summary>
        internal static string CapacitiesLabel {
            get {
                return ResourceManager.GetString("CapacitiesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charge.
        /// </summary>
        internal static string charge {
            get {
                return ResourceManager.GetString("charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charges.
        /// </summary>
        internal static string charges {
            get {
                return ResourceManager.GetString("charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décisions.
        /// </summary>
        internal static string Choices {
            get {
                return ResourceManager.GetString("Choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tout progrès depuis la dernière sauvegarde sera perdu, êtes vous sûr ?.
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poignard.
        /// </summary>
        internal static string Dagger {
            get {
                return ResourceManager.GetString("Dagger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommages Subi :.
        /// </summary>
        internal static string DamageTaken {
            get {
                return ResourceManager.GetString("DamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre agilité est réduite !.
        /// </summary>
        internal static string DebuffAgility {
            get {
                return ResourceManager.GetString("DebuffAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lors un combat.
        /// </summary>
        internal static string DuringBattle {
            get {
                return ResourceManager.GetString("DuringBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saisir un Nom :.
        /// </summary>
        internal static string EnterCharacterName {
            get {
                return ResourceManager.GetString("EnterCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas vous enfuir ainsi !.
        /// </summary>
        internal static string ErrorEscape {
            get {
                return ResourceManager.GetString("ErrorEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre inventaire est plein ! vous devez vider un objet de votre sac avant de pouvoir récupérer un nouvel item.
        /// </summary>
        internal static string ErrorInventoryFull {
            get {
                return ResourceManager.GetString("ErrorInventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez pas assez de pièces d&apos;or !.
        /// </summary>
        internal static string ErrorNotEnoughtGold {
            get {
                return ResourceManager.GetString("ErrorNotEnoughtGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur, impossible de sauvegarder le héro !.
        /// </summary>
        internal static string ErrorSaving {
            get {
                return ResourceManager.GetString("ErrorSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre baudrier est plein ! vous devez jeter une arme avant de pouvoir en récupérer une nouvelle.
        /// </summary>
        internal static string ErrorWeaponHolderFull {
            get {
                return ResourceManager.GetString("ErrorWeaponHolderFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;enfuir.
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nourriture.
        /// </summary>
        internal static string food {
            get {
                return ResourceManager.GetString("food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rassasié.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pièces d&apos;or.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aller au Menu de Chargement ?.
        /// </summary>
        internal static string GoToLoadingMenu {
            get {
                return ResourceManager.GetString("GoToLoadingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guérison.
        /// </summary>
        internal static string Healing {
            get {
                return ResourceManager.GetString("Healing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champion.
        /// </summary>
        internal static string Hero {
            get {
                return ResourceManager.GetString("Hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caractéristiques Héro.
        /// </summary>
        internal static string HeroStats {
            get {
                return ResourceManager.GetString("HeroStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camouflage.
        /// </summary>
        internal static string Hiding {
            get {
                return ResourceManager.GetString("Hiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points de Vie :.
        /// </summary>
        internal static string HitPoints {
            get {
                return ResourceManager.GetString("HitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PdV.
        /// </summary>
        internal static string HP {
            get {
                return ResourceManager.GetString("HP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humain.
        /// </summary>
        internal static string Human {
            get {
                return ResourceManager.GetString("Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satiété :.
        /// </summary>
        internal static string Hunger {
            get {
                return ResourceManager.GetString("Hunger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affamé.
        /// </summary>
        internal static string Hungry {
            get {
                return ResourceManager.GetString("Hungry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maitrise de la Chasse.
        /// </summary>
        internal static string Hunting {
            get {
                return ResourceManager.GetString("Hunting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventaire.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pièces d&apos;Or :.
        /// </summary>
        internal static string LabelGold {
            get {
                return ResourceManager.GetString("LabelGold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points de Vie :.
        /// </summary>
        internal static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des Capacités.
        /// </summary>
        internal static string ListCapacities {
            get {
                return ResourceManager.GetString("ListCapacities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu de Chargement.
        /// </summary>
        internal static string LoadMenu {
            get {
                return ResourceManager.GetString("LoadMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masse.
        /// </summary>
        internal static string Mace {
            get {
                return ResourceManager.GetString("Mace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu des Capacitiés.
        /// </summary>
        internal static string MenuCapacities {
            get {
                return ResourceManager.GetString("MenuCapacities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle Partie.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prochain Round.
        /// </summary>
        internal static string NextRound {
            get {
                return ResourceManager.GetString("NextRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SansNom.
        /// </summary>
        internal static string NoName {
            get {
                return ResourceManager.GetString("NoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orc.
        /// </summary>
        internal static string Orc {
            get {
                return ResourceManager.GetString("Orc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to permanent.
        /// </summary>
        internal static string permanent {
            get {
                return ResourceManager.GetString("permanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puissance Psychique.
        /// </summary>
        internal static string PsychicPower {
            get {
                return ResourceManager.GetString("PsychicPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bouclier Psychique.
        /// </summary>
        internal static string PsychicShield {
            get {
                return ResourceManager.GetString("PsychicShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round numéro.
        /// </summary>
        internal static string RoundNumber {
            get {
                return ResourceManager.GetString("RoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabre.
        /// </summary>
        internal static string Sabre {
            get {
                return ResourceManager.GetString("Sabre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir un Nom de Personnage.
        /// </summary>
        internal static string SelectCharacterName {
            get {
                return ResourceManager.GetString("SelectCharacterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixième Sens.
        /// </summary>
        internal static string SixthSense {
            get {
                return ResourceManager.GetString("SixthSense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lance.
        /// </summary>
        internal static string Spear {
            get {
                return ResourceManager.GetString("Spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objets Spéciaux :.
        /// </summary>
        internal static string SpecialItems {
            get {
                return ResourceManager.GetString("SpecialItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débuter le combat.
        /// </summary>
        internal static string StartFight {
            get {
                return ResourceManager.GetString("StartFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Héro sauvegardé avec succès !.
        /// </summary>
        internal static string SuccesSaving {
            get {
                return ResourceManager.GetString("SuccesSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Épée.
        /// </summary>
        internal static string Sword {
            get {
                return ResourceManager.GetString("Sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous subissez des dégats !.
        /// </summary>
        internal static string TakeDamage {
            get {
                return ResourceManager.GetString("TakeDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maitrise de la matière.
        /// </summary>
        internal static string Telekinesis {
            get {
                return ResourceManager.GetString("Telekinesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeter l&apos;objet.
        /// </summary>
        internal static string ThrowItem {
            get {
                return ResourceManager.GetString("ThrowItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeter l&apos;arme.
        /// </summary>
        internal static string ThrowWeapon {
            get {
                return ResourceManager.GetString("ThrowWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glaive.
        /// </summary>
        internal static string TwoEdgedSword {
            get {
                return ResourceManager.GetString("TwoEdgedSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser votre capacité .
        /// </summary>
        internal static string UseCapacity {
            get {
                return ResourceManager.GetString("UseCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser l&apos;objet.
        /// </summary>
        internal static string UseItem {
            get {
                return ResourceManager.GetString("UseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Victoire.
        /// </summary>
        internal static string Victory {
            get {
                return ResourceManager.GetString("Victory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marteau de Guerre.
        /// </summary>
        internal static string WarHammer {
            get {
                return ResourceManager.GetString("WarHammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armes :.
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maitrise des Armes.
        /// </summary>
        internal static string WeaponMastery {
            get {
                return ResourceManager.GetString("WeaponMastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maitrise des Armes :.
        /// </summary>
        internal static string WeaponMasteryLabel {
            get {
                return ResourceManager.GetString("WeaponMasteryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes mort ! Bonne chance pour la prochaine fois..
        /// </summary>
        internal static string YouDied {
            get {
                return ResourceManager.GetString("YouDied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous Devez Combattre !.
        /// </summary>
        internal static string YouMustFight {
            get {
                return ResourceManager.GetString("YouMustFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez selectionner.
        /// </summary>
        internal static string YouMustSelect {
            get {
                return ResourceManager.GetString("YouMustSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre Adversaire :.
        /// </summary>
        internal static string YourEnemy {
            get {
                return ResourceManager.GetString("YourEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre Héro :.
        /// </summary>
        internal static string YourHero {
            get {
                return ResourceManager.GetString("YourHero", resourceCulture);
            }
        }
    }
}
