//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LDVELH_WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LDVELH_WPF.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilité :.
        /// </summary>
        internal static string Agility {
            get {
                return ResourceManager.GetString("Agility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sac à Dos :.
        /// </summary>
        internal static string BackPack {
            get {
                return ResourceManager.GetString("BackPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En Combat.
        /// </summary>
        internal static string Battling {
            get {
                return ResourceManager.GetString("Battling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacités :.
        /// </summary>
        internal static string Capacities {
            get {
                return ResourceManager.GetString("Capacities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Décisions.
        /// </summary>
        internal static string Choices {
            get {
                return ResourceManager.GetString("Choices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dommages Subi :.
        /// </summary>
        internal static string DamageTaken {
            get {
                return ResourceManager.GetString("DamageTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;enfuir.
        /// </summary>
        internal static string Escape {
            get {
                return ResourceManager.GetString("Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pièces d&apos;Or :.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caractéristiques Héro.
        /// </summary>
        internal static string HeroStats {
            get {
                return ResourceManager.GetString("HeroStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points de Vie :.
        /// </summary>
        internal static string HitPoints {
            get {
                return ResourceManager.GetString("HitPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satiété :.
        /// </summary>
        internal static string Hunger {
            get {
                return ResourceManager.GetString("Hunger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventaire.
        /// </summary>
        internal static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points de Vie :.
        /// </summary>
        internal static string Life {
            get {
                return ResourceManager.GetString("Life", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des Capacités.
        /// </summary>
        internal static string ListCapacities {
            get {
                return ResourceManager.GetString("ListCapacities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu de Chargement.
        /// </summary>
        internal static string LoadMenu {
            get {
                return ResourceManager.GetString("LoadMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu des Capacitiés.
        /// </summary>
        internal static string MenuCapacities {
            get {
                return ResourceManager.GetString("MenuCapacities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle Partie.
        /// </summary>
        internal static string NewGame {
            get {
                return ResourceManager.GetString("NewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objets Spéciaux :.
        /// </summary>
        internal static string SpecialItems {
            get {
                return ResourceManager.GetString("SpecialItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Débuter le combat.
        /// </summary>
        internal static string StartFight {
            get {
                return ResourceManager.GetString("StartFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jet l&apos;objet.
        /// </summary>
        internal static string ThrowItem {
            get {
                return ResourceManager.GetString("ThrowItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeter l&apos;arme.
        /// </summary>
        internal static string ThrowWeapon {
            get {
                return ResourceManager.GetString("ThrowWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utiliser l&apos;objet.
        /// </summary>
        internal static string UseItem {
            get {
                return ResourceManager.GetString("UseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armes :.
        /// </summary>
        internal static string Weapon {
            get {
                return ResourceManager.GetString("Weapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maitrise des Armes :.
        /// </summary>
        internal static string WeaponMastery {
            get {
                return ResourceManager.GetString("WeaponMastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous Devez Combattre !.
        /// </summary>
        internal static string YouMustFight {
            get {
                return ResourceManager.GetString("YouMustFight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre Adversaire :.
        /// </summary>
        internal static string YourEnemy {
            get {
                return ResourceManager.GetString("YourEnemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre Héro :.
        /// </summary>
        internal static string YourHero {
            get {
                return ResourceManager.GetString("YourHero", resourceCulture);
            }
        }
    }
}
