// <auto-generated />
namespace LDVELH_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DatabaseWorking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabaseWorking));
        
        string IMigrationMetadata.Id
        {
            get { return "201606141512290_DatabaseWorking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
